name: hope
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.7.0
  rxdart: ^0.27.7
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0
  path: ^1.8.2
  geolocator: ^9.0.2
  http: ^0.13.6
  path_provider: ^2.0.15
  network_to_file_image: ^4.0.1
  permission_handler: ^10.2.0
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  calendar_date_picker2: ^0.5.2
  memory_cache: ^1.2.0
  dropdown_button2: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf